#!/bin/bash

 # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                                                     #
#   Process IP's and MAC's for importing into Nessus  #
#                                                     #
 # # # # # # # # # # # # # # # # # # # # # # # # # # #

 # # # # # # # # # # # # # # # # # # # # # # # # # # #
#   list the IP's of the unique MAC's                 #
 # # # # # # # # # # # # # # # # # # # # # # # # # # #
egrep -i poodle /mnt/global/nmap/reports/nmap-vuln-devices.report | egrep -iv 'cve|^$' | sort -uk3,3 | cut -f2 > /mnt/global/nmap/reports/nessus/nmap_nessus_ip_poodle.tmp

 # # # # # # # # # # # # # # # # # # # # # # # # # # #
#   appending devices that do not list MAC's          #
 # # # # # # # # # # # # # # # # # # # # # # # # # # #
egrep -i poodle /mnt/global/nmap/reports/report_vuln.log | egrep -iv 'cve|^$' | cut -f2 >> /mnt/global/nmap/reports/nessus/nmap_nessus_ip_poodle.tmp

 # # # # # # # # # # # # # # # # # # # # # # # # # # #
#   unique IP's are sorted                            #
 # # # # # # # # # # # # # # # # # # # # # # # # # # #
sort -u /mnt/global/nmap/reports/nessus/nmap_nessus_ip_poodle.tmp | /usr/local/flowtools/bin/ipsort.pl > /mnt/global/nmap/reports/nessus/nmap_nessus_ip_poodle.import

 # # # # # # # # # # # # # # # # # # # # # # # # # # #
#   clean tmps                                        #
 # # # # # # # # # # # # # # # # # # # # # # # # # # #
rm /mnt/global/nmap/reports/nessus/nmap_nessus_ip_poodle.tmp

 # # # # # # # # # # # # # # # # # # # # # # # # # # #
#   list the unique MACs                              #
 # # # # # # # # # # # # # # # # # # # # # # # # # # #
egrep -i poodle /mnt/global/nmap/reports/report_vuln.log | egrep -iv 'cve|^$' | sort -uk3,3 | cut -f3 | sort -n > /mnt/global/nmap/reports/nessus/nmap_nessus_mac_poodle.import

 # # # # # # # # # # # # # # # # # # # # # # # # # # #
#   rotate and archive the logs                       #
 # # # # # # # # # # # # # # # # # # # # # # # # # # #
#/usr/sbin/logrotate /etc/logrotate.d/nmap_log
